name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [ "bug" ]
assignees:
  - noahhusby
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: "Describe the steps it takes to reproduce the bug Example:."
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Sledgehammer Version
      description: "What version of Sledgehammer is running?"
      placeholder: "0.5.0"
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Log File
      description: "If applicable, paste your server logs into [https://mclo.gs](https://mclo.gs/)."
      placeholder: "https://mclo.gs/..."
    validations:
      required: false
  - type: dropdown
    id: backend
    attributes:
      label: Server Type
      description: "If applicable, which MC server type are you running?"
      options:
        - Bukkit
        - Spigot
        - Paper
        - Mohist
        - Forge
        - Other
    validations:
      required: false
