name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: [ "enhancement" ]
assignees:
  - noahhusby
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature
      description: "Is your feature request related to a problem? Please describe."
    validations:
      required: true